### ISSUE TITLE
dont work since update

### ISSUE THREAD

**Issue by aymhce** [abeudin/ampache_ynh#12]
Hello,

A think my issue is since this commit : https://github.com/abeudin/ampache_ynh/commit/c730a08b3c34212f4e5a4cdefb47616574b4707d

@stevenroose can you see it please ?

Issue after ampache install/update : 
```[FAIL] Restarting nginx: nginx failed!```

In my nginx error log : 
```
2015/09/07 22:36:54 [emerg] 7869#0: location "bin/" is outside location "/ampache" in /etc/nginx/conf.d/***************.d/ampache.conf:20
```

**Comment by stevenroose** [comment]
I'm sorry, I copied that part from the Ampache wiki and forgot to translate the path to be Yunohost-compliant.
Should be fixed by my PR here: https://github.com/abeudin/ampache_ynh/pull/13
